# Generated by Django 4.1.1 on 2023-05-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
