# Generated by Django 4.1.1 on 2023-05-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='slug',
        ),
    ]
