# Generated by Django 4.1.1 on 2023-05-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_department_slug_remove_project_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(default='doc', upload_to='documents'),
            preserve_default=False,
        ),
    ]
